### ISSUE TITLE
Clean up open issues

### ISSUE THREAD

**Issue by mdesco18** [uvicgse/project-virtual-team-2#104]
From project-seed

Problem
The open issues have varying documentation quality.
Also, some of the open issues have been resolved.

Task
For each open issue in your teams repo, attempt to reproduce the issue.
If the issue no longer exists, close the issue with an informative comment.

If the issue is still outstanding, make sure the documentation is clear.
You will need to add to or modify the current documentation where appropriate.

This includes:

Modifying the issue title, if its too cryptic currently
Give a clear description of the issue
In the case of a bug, give clear steps to reproduce.
Provide screenshots

**Comment by jbenning97** [comment]
### Issue cleanup summary

Issue #2: Pushed a hotfix to corresponding branch, still have to create PR
Issue #4: Issue still exists, documentation is clear, title accurate
Issue #5: Unable to reproduce, requested more info from Matthew Smith
Issue #6: Unable to reproduce because of infinite loading
Issue #12: Fixed and closed
Issue #13: Renamed, added commenting
Issue #16: Still exists
Issue #17: Unable to reproduce, added comment
Issue #18: Still exists, added further comment
Issue #20: In progress
Issue #21: Enhancement still required
Issue #22: Still exists
Issue #23: Possibly fixed, requested more info from Matthew Smith
Issue #24: Fixed and closed
Issue #25: Currently in todo
Issue #26: Still exists
Issue #27: Fixed and closed
Issue #28: Unable to continue without signing in so unable to reproduce
Issue #29: Still exists
Issue #30: Currently in todo
Issue #32: Currently in todo
Issue #33: Still exists
Issue #34: In progress
Issue #36: Still exists
Issue #37: Still exists
Issue #38: Still exists
Issue #39: In progress
Issue #40: In progress
Issue #41: Resolved and closed due to inactivity and it possibly being fixed in an upgrade
Issue #42: Could not replicate as I am not running Ubuntu. Will assume still exists
Issue #43: Could not replicate but leaving open if it is a machine-specific issue
Issue #44: Fixed, closed issue
Issue #45: Still exists
Issue #46: Still exists
Issue #47: Still exists
Issue #54: Still exists
Issue #57: Still exists
Issue #62: In progress
Issue #72: Still exists
Issue #73: Still exists but would be solved by the Oauth implementation
Issue #76: In progress
Issue #84: In progress
Issue #89: In progress
Issue #101: In progress
Issue #103: In progress
Issue #104: Current issue. Recursion is causing infinite loop. On to the next issue
Issue #106: In progress
Issue #107: In progress
Issue #118: In progress
Issue #120: In progress
Issue #121: In progress
