### ISSUE TITLE
Use Oauth instead of storing the username and password in data.json

### ISSUE THREAD

**Issue by ovrynn** [uvicgse/project-virtual-team-2#20]
Saving the token from Github's Oauth would be more secure than storing a encrypted password in data.json.

**Comment by Leon0315** [comment]
The current electron version does not support by Github when trying to login. Need to upgrade electron, node and possibly Angular version in order to authorize user. The button is unclickable because the version is too old

<img width="745" alt="Screen Shot 2019-06-09 at 5 06 52 PM" src="https://user-images.githubusercontent.com/15313467/59166023-592a6e00-8ad9-11e9-9633-24b707bc2cad.png">

**Comment by Leon0315** [comment]
Once we upgraded to new version of electron & Node, we have options to use npm library like [electron-oauth-helper](https://www.npmjs.com/package/electron-oauth-helper) or [oauth-electron](https://www.npmjs.com/package/oauth-electron) to process access token. Currently, we wrote the code ourselves to handle the access token, but unable to test it due to old version of electron.

**Comment by Leon0315** [comment]
Progress:

- UI done
<img width="423" alt="Screen Shot 2019-06-11 at 9 27 12 PM" src="https://user-images.githubusercontent.com/15313467/59323484-af411200-8c8f-11e9-9a7c-f3407cbea3e2.png">

- Code to handle access token. Done, commented.
- Store, encrypt, and retrieve and token. Done
- Were able to login and push to remote successfully with hard coded access token.

TODO:
- ~~Upgrade electron and Node #99~~
- ~~Test our own code or use Oauth npm library~~
- Testing Pull request #94

**Comment by Leon0315** [comment]
closed via #94
