### ISSUE TITLE
Add commenting to past commits

### ISSUE THREAD

**Issue by ovrynn** [uvicgse/project-virtual-team-2#34]
Currently, you are unable to see any comments on past commits within VisualGit. It would be useful to be able to view all the commit comments and then be able to add or edit new commit messages. 

These are the comments/messages entered when a commit is made.
They can be viewed in the terminal using the command, _:git log_ (shown below) 
![image](https://user-images.githubusercontent.com/22312351/58907659-90f17a00-86c3-11e9-8f09-25013745c20e.png)

The implementation of this feature is open to discussion.

**Comment by zeshili** [comment]
This was a research task for Group 6's Sprint 3.

**Comment by SrishtiSinghal** [comment]
Overview: 
This comment is for the documentation of the research done on displaying and modifying past commit messages. Since we already implemented the display functionality of the past commit messages (commit history) for a different issue, first part of the research is complete. 

Key Findings:
For the modify functionality, we didn't find a nodegit solution to edit any commit message we want. However it is possible to implement the modify functionality for the most recent commit. On the command line, to edit the most recent commit, we use the command git commit --amend -m "the new commit message".  To implement the modify commit in visualgit we can use the nodegit commit #amend async functionality. https://www.nodegit.org/api/commit/ 

Timeline:
If we were to implement the modify commit message functionality for the most recent commit, we will create an edit button and add it besides the commit history in the graphing model. When we click on this button, it should give us the most recent commit and with the use of nodegit api for amend commit, we should be able to modify it. It seems like it will be really difficult to implement it but it is definitely possible to do so.
