### ISSUE TITLE
Compiling the existing master code causes the revision history graph to disappear

### ISSUE THREAD

**Issue by ovrynn** [uvicgse/project-virtual-team-2#41]
The repository window should look like this when a change is made:

![image](https://user-images.githubusercontent.com/22312351/57722145-f3b1b000-76d9-11e9-89e8-e7dcf1d5bb82.png)

After compiling the code the graph disappears and the window looks like this:

![image](https://user-images.githubusercontent.com/22312351/57722176-00360880-76da-11e9-9277-105885955eae.png)

**Comment by jbenning97** [comment]
@mdesco18 Do you understand what's going on here?

**Comment by mdesco18** [comment]
@jbenning97 this is such a primitive version of the app and nobody has mentioned this issue in sprints or in new issues. I'd consider it closed. The confusion comes from 

> After compiling the code

Since that wouldn't affect the current instance of Visual Git unless the user reloads.
If the user rebuilds the application code or even refreshes the graph, and this doesn't happen anymore, then this is closed.

**Comment by jbenning97** [comment]
Closed due to inactivity and it possibly being fixed in an upgrade
