### ISSUE TITLE
Display status of local repo

### ISSUE THREAD

**Issue by smithmr** [uvicgse/project-virtual-team-2#88]
## functionality
- display status of local branch compared to the origin branch

## statuses
- up to date
- behind (number behind)
- ahead (number of commits)
- origin does not exist

**Comment by ajlarivi** [comment]
**general idea for implementation:**
- create a div in footer app/components/footer.component.html on right hand side with id "ahead-behind-display"
- use an interpolation (ie. {{commits}}) in order to display ahead or behind
------------------------------------
- create function displayAheadBehind() in app/misc/git.ts
- run getAheadBehindCommits() process the returned object to get the number to display
- elem = document.getElementById('ahead-behind-display')
- elem.commits = x
------------------------------------
- add displayAheadBehind() function to setInterval() in index.html

**Comment by smithmr** [comment]
> **general idea for implementation:**
> 
> * create a div in footer app/components/footer.component.html on right hand side with id "ahead-behind-display"
> * use an interpolation (ie. {{commits}}) in order to display ahead or behind
> 
> * create function displayAheadBehind() in app/misc/git.ts
> * run getAheadBehindCommits() process the returned object to get the number to display
> * elem = document.getElementById('ahead-behind-display')
> * elem.commits = x
> 
> * add displayAheadBehind() function to setInterval() in index.html

We need to create a "gitFetch" function, as well. The status button should fetch if you click it.

**Comment by ajlarivi** [comment]
Product owner requested fetch button be moved to the header and an indicator added to the status saying you need to fetch.
